### ISSUE TITLE
Class constructor ...Middleware cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Ionaru** [Romakita/ts-express-decorators#129]
I am trying to overwrite the GlobalErrorHandlerMiddleware, but I am getting this error:
`Class constructor ErrorHandlerMiddleware cannot be invoked without 'new'`

Full stacktrace:
```
TypeError: Class constructor ErrorHandlerMiddleware cannot be invoked without 'new'
    at HandlerBuilder.<anonymous> (/home/jeroen.akkerman/Projects/typescript-express/node_modules/ts-express-decorators/src/mvc/class/HandlerBuilder.ts:169:47)
    at step (/home/jeroen.akkerman/Projects/typescript-express/node_modules/tslib/tslib.js:122:27)
    at Object.next (/home/jeroen.akkerman/Projects/typescript-express/node_modules/tslib/tslib.js:103:57)
    at /home/jeroen.akkerman/Projects/typescript-express/node_modules/tslib/tslib.js:96:75
    at Promise (<anonymous>)
    at Object.__awaiter (/home/jeroen.akkerman/Projects/typescript-express/node_modules/tslib/tslib.js:92:16)
    at HandlerBuilder.invoke (/home/jeroen.akkerman/Projects/typescript-express/node_modules/ts-express-decorators/lib/mvc/class/HandlerBuilder.js:163:24)
    at /home/jeroen.akkerman/Projects/typescript-express/node_modules/ts-express-decorators/src/mvc/class/HandlerBuilder.ts:58:29
    at Layer.handle [as handle_request] (/home/jeroen.akkerman/Projects/typescript-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/jeroen.akkerman/Projects/typescript-express/node_modules/express/lib/router/index.js:317:13)
```

My new error handler:
```typescript
import { NextFunction as ExpressNext, Request as ExpressRequest, Response as ExpressResponse } from 'express';
import {
    Err,
    GlobalErrorHandlerMiddleware,
    IMiddlewareError,
    Next,
    OverrideMiddleware,
    Request,
    Response,
} from 'ts-express-decorators';
import { $log } from 'ts-log-debug';

@OverrideMiddleware(GlobalErrorHandlerMiddleware)
export class ErrorHandlerMiddleware implements IMiddlewareError {

    public use(@Err() error: any, @Request() request: ExpressRequest, @Response() response: ExpressResponse,
               @Next() next: ExpressNext): any {

        $log.error(error);
        response.status(error.status || 500);
        response.render('error', {error});
    }
}
```

server.ts:
```typescript
public $onMountingMiddlewares(): void {

    // Register error handler first.
    this.use(ErrorHandlerMiddleware);

    // ... rest of the server code
}
```

Environment:
Node 8.6.0
NPM 5.4.2
ts.ED 2.3.9

**Comment by Ionaru** [comment]
Looks like this is caused by setting `"target": "es6"` in `tsconfig.json`. But I'm not sure why.

**Comment by vologab** [comment]
@Ionaru You don't need to do `this.use(ErrorHandlerMiddleware)` in case of `@OverrideMiddleware` (see example - https://romakita.github.io/ts-express-decorators/#/docs/middlewares/override-middleware), otherwise apply `@MiddlewareError()` or `@Middleware()`. Am I right @Romakita  ?

**Comment by Romakita** [comment]
@vologab It's right :). Thanks for your answer ^^

@Ionaru OverrideMiddleware will replace the original middleware that is already invoked by Ts.ED (if it's an internal Ts.ED middlewares like GlobalErrorHandlerMiddleware).

See you :)

**Comment by Ionaru** [comment]
If I don't do `this.use(ErrorHandlerMiddleware)`, the handler will only output the error text instead of rendering it in a template.

**Comment by Romakita** [comment]
It's strange... I didn't understand why you need to call the ErrorHandler before all others middlewares, in this example: 

```typescript
public $onMountingMiddlewares(): void {

    // Register error handler first.
    this.use(ErrorHandlerMiddleware);

    // ... rest of the server code
}
```

GlobalErrorHandlerMiddleware is added at the end of the middlewares list, after the $afterInitRoutes  hook is called (see [lifecycle hooks](https://romakita.github.io/ts-express-decorators/#/docs/server-loader/lifecycle-hooks)). So maybe isn't the behavior that you want.

But according to your example, you just need to declare a Middleware insteadof Override GlobalErrorHandlerMiddleware.

```typescript
import { NextFunction as ExpressNext, Request as ExpressRequest, Response as ExpressResponse } from 'express';
import {
    Err,
    GlobalErrorHandlerMiddleware,
    IMiddlewareError,
    Next,
    MiddlewareError,
    Request,
    Response,
} from 'ts-express-decorators';
import { $log } from 'ts-log-debug';

@MiddlewareError()
export class ErrorHandlerMiddleware implements IMiddlewareError {

    public use(@Err() error: any, @Request() request: ExpressRequest, @Response() response: ExpressResponse,
               @Next() next: ExpressNext): any {

        $log.error(error);
        response.status(error.status || 500);
        response.render('error', {error});
    }
}
```
Try this example :)

But if your need is to handle all errors, the override method is the good way. I'll check if we haven't a bug with the rendering method when error is handle...

See you,
Romain

**Comment by Romakita** [comment]
With Override method, this example work:
```typescript
import {Exception} from "ts-httpexceptions";
import {$log} from "ts-log-debug";
import {GlobalErrorHandlerMiddleware, OverrideMiddleware, Err, Next, Req, Res} from "ts-express-decorators";

@OverrideMiddleware(GlobalErrorHandlerMiddleware)
export class CustomErrorHandlerMiddleware {
    /**
     * Custom error management
     * @param error
     * @param request
     * @param response
     * @param next
     * @returns {any}
     */
    use(@Err() error: any, @Req() request: any, @Res() response: any, @Next() next: any) {
        const toHTML = (message = "") => message.replace(/\n/gi, "<br />");

        if (error instanceof Exception || error.status) {
            $log.error("" + error);
            response.status(error.status).send(toHTML(error.message));
            return next();
        }

        if (typeof error === "string") {
            response.status(404).send(toHTML(error));
            return next();
        }

        $log.error(error);
        response.status(error.status || 500);
        response.render("error500", {error});
    }
}
```
