### ISSUE TITLE
Cannot set port in ServerSettings to environment variable on azure app service

### ISSUE THREAD

**Issue by Soulskater** [Romakita/ts-express-decorators#142]
Trying to use this config:
`port: process.env.PORT || 8080`
This works on local or heroku for instance, but in azure the enviroment port variable is something like \\.\pipe\e8e054ce-f7b0-4903-9af4-6ceba48a2285

So i get runtime error on app start because there is a validation or something, it says the port should be a number.

**Comment by Romakita** [comment]
Hi @Soulskater 

I'm not sure but can you try to override the startServer and redeploy on azure. Here the fix:

```typescript

class Server extends ServerLoader {
    protected startServer(http: any, settings: { https: boolean, address: string, port: string | number | false }) {
        const {address, port, https} = settings;

        $log.debug(`Start server on ${https ? "https" : "http"}://${settings.address}:${settings.port}`);
        const promise = new Promise((resolve, reject) => {
            http
                .on("listening", resolve)
                .on("error", reject);
        })
            .then(() => {
                $log.info(`HTTP Server listen on ${https ? "https" : "http"}://${settings.address}:${settings.port}`);
            });

        http.listen(port, address);
        return promise;
    }
}
```

Said me if it work and I'll publish a fix ASAP ;)

See you,
Romain

**Comment by Soulskater** [comment]
Seems this fix works!
Could you update the package?
Thanks!

**Comment by lwallent** [comment]
Hi @Soulskater

You should be able to specify the port the same way on Azure.
````
port: process.env.PORT || 8080
````
should work fine.

Have you setup your web.config correctly for iisnode to run the node process?

What is printed in your log during startup?

KR
Lasse

**Comment by Soulskater** [comment]
Here is the error
`ERROR] [TSED] - RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1393:5)
    at ServerLoader.startServer (D:\home\site\wwwroot\node_modules\ts-express-decorators\src\server\components\ServerLoader.ts:300:14)
    at Server.<anonymous> (D:\home\site\wwwroot\node_modules\ts-express-decorators\src\server\components\ServerLoader.ts:314:32)
    at step (D:\home\site\wwwroot\node_modules\tslib\tslib.js:129:27)
    at Object.next (D:\home\site\wwwroot\node_modules\tslib\tslib.js:110:57)
    at D:\home\site\wwwroot\node_modules\tslib\tslib.js:103:75
    at Object.__awaiter (D:\home\site\wwwroot\node_modules\tslib\tslib.js:99:16)
    at ServerLoader.startServers (D:\home\site\wwwroot\node_modules\ts-express-decorators\lib\server\components\ServerLoader.js:302:24)
    at Server.<anonymous> (D:\home\site\wwwroot\node_modules\ts-express-decorators\src\server\components\ServerLoader.ts:265:24)
    at step (D:\home\site\wwwroot\node_modules\tslib\tslib.js:129:27)
    at Object.next (D:\home\site\wwwroot\node_modules\tslib\tslib.js:110:57)
    at fulfilled (D:\home\site\wwwroot\node_modules\tslib\tslib.js:100:62)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

The url is http://0.0.0.0:NaN/api-docs this seems to me that the port was simply converted to number.

**Comment by Soulskater** [comment]
I also modified this function:
`ServerSettingsService.buildAddressAndPort = function (addressPort) {
        var address = "0.0.0.0";
        var port = addressPort;
        if (typeof addressPort === "string" && addressPort.indexOf(":") > -1) {
            _a = addressPort.split(":"), address = _a[0], port = _a[1];
        }
        return { address: address, port: port };
        var _a;
    };`

Now my azure app service is up and running!
Could you guys create a quick fix with changes @Romakita  and my changes?

Thanks for your help!
