### ISSUE TITLE
Injecting Factory in $onAuth

### ISSUE THREAD

**Issue by FrozenDroid** [Romakita/ts-express-decorators#144]
## Informations

Type | Version
---|---
Question | 2.6.4

****

## Description
In my $onAuth, I need to use a Factory. This factory contains the Firebase Admin API. With that, I check whether or not the user is authenticated.  
How would I go about doing that the best way? Currently I'm just grabbing the `InjectorService` and getting the factory through there, but I feel like that's not how it's supposed to be done.  
Is there a better way of doing this?

**Comment by Romakita** [comment]
Normally you can do that:

```typescript
@Inject()
$onAuth(@Inject(MyFactory) myFactory: MyFactory ) {

}
```

See you :)

**Comment by FrozenDroid** [comment]
I've tried that:
```js
@Inject()
public $onAuth(@Inject(Firebase) firebase: Firebase) {}
```
But when I do that, I get:
```
TypeError: Cannot read property 'prototype' of undefined
    at Object.getClass (/Users/vincent/Code/Nodejs/x/node_modules/ts-express-decorators/src/core/utils/index.ts:23:19)
    at Function.Metadata.set (/Users/vincent/Code/Nodejs/x/node_modules/ts-express-decorators/src/core/class/Metadata.ts:424:34)
    at Function.Metadata.setParamTypes (/Users/vincent/Code/Nodejs/x/node_modules/ts-express-decorators/src/core/class/Metadata.ts:371:21)
    at /Users/vincent/Code/Nodejs/x/node_modules/ts-express-decorators/src/di/decorators/inject.ts:19:26
    at /Users/vincent/Code/Nodejs/x/dist/Server.js:12:37
    at DecorateProperty (/Users/vincent/Code/Nodejs/x/node_modules/reflect-metadata/Reflect.ts:1102:31)
    at Object.decorate (/Users/vincent/Code/Nodejs/x/node_modules/reflect-metadata/Reflect.ts:279:20)
    at __decorate (/Users/vincent/Code/Nodejs/x/dist/Server.js:4:92)
    at Object.<anonymous> (/Users/vincent/Code/Nodejs/x/dist/Server.js:43:1)
    at Module._compile (module.js:624:30)
```

**Comment by Romakita** [comment]
Have declared firebase as a factory ?

```typescript
import * as Firebase from "firebase";

export interface Firebase {
}
export const Firebase = Symbol("Firebase");
```

**Comment by FrozenDroid** [comment]
FirebaseAdmin.ts:
```js
import {InjectorService} from 'ts-express-decorators';
import * as firebase from 'firebase-admin';
import * as fs from 'fs';

export interface IFirebase {
    getAdmin(): firebase.app.App;
}

export type Firebase = IFirebase;
export const Firebase = Symbol('Firebase');

const admin = firebase.initializeApp({
    credential: firebase.credential.cert(
        JSON.parse(fs.readFileSync(
            './service_account.json',
        ).toString()),
    ),
});

InjectorService.factory(Firebase, {
    getAdmin: () => admin,
});

```

**Comment by Romakita** [comment]
I think in your case, @OverrideMiddleware can to be the right way:

```typescript
@OverrideMiddleware(AuthenticatedMiddleware)
export class FirebaseAuthMiddleware implements IMiddleware {

    constructor(private serverSettingsService: ServerSettingsService) { }

    public use(@EndpointInfo() endpoint: EndpointMetadata,
               @Request() request: Express.Request,
               @Response() response: Express.Response,
               @Next() next: Express.NextFunction) {

        const options = endpoint.get(AuthenticatedMiddleware) || {};
        if (!Firebase.isAuth){ // something like that ;)
           next(new Forbidden("Forbidden"));
        }
        next();
    }
}

```

**Comment by FrozenDroid** [comment]
I'll try this out in a bit :)

**Comment by Romakita** [comment]
Be aware, if you use the OverrideMiddleware decorator on AuthenticathedMiddleware, the $onAuth hook in your server will be avoided ;)
