### ISSUE TITLE
Importing 'ajv' module breaks npm scripts

### ISSUE THREAD

**Issue by therealTP** [Romakita/ts-express-decorators#169]
## Information
Question | 2.14.1
****
## Description
When I try to import the new 'ajv' validation feature into a TS file (import ts-express-decorators/ajv), npm start script fails with the following error:

`Error: Cannot find module '../../../src/ajv'`

I also get an error when I run npm install:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test-ts-express-decorator@1.0.0 tsc: `tsc  --project tsconfig.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the test-ts-express-decorator@1.0.0 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I've installed the AJV npm package & the install/start scripts run fine after I remove the import of ajv from my ts file. I've tried the following:
- Reinstalling Node & NPM (using npm@5.5.1 & using node@v8.9.1)
- Deleting node_modules & reinstalling
- Deleting ts-express-decorators and reinstalling
- Deleting ajv and reinstalling

Any ideas here? Been banging my head on the table for awhile now. Thanks!

**Comment by therealTP** [comment]
Here is the full npm log from the failed npm install:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info lifecycle test-ts-express-decorator@1.0.0~pretsc: test-ts-express-decorator@1.0.0
6 info lifecycle test-ts-express-decorator@1.0.0~tsc: test-ts-express-decorator@1.0.0
7 verbose lifecycle test-ts-express-decorator@1.0.0~tsc: unsafe-perm in lifecycle true
8 verbose lifecycle test-ts-express-decorator@1.0.0~tsc: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Tyler/Projects/ts-decorators-example/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Tyler/Projects/ts-decorators-example/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Tyler/Projects/ts-decorators-example/node_modules/.bin:/Users/Tyler/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/Tyler/bin
9 verbose lifecycle test-ts-express-decorator@1.0.0~tsc: CWD: /Users/Tyler/Projects/ts-decorators-example
10 silly lifecycle test-ts-express-decorator@1.0.0~tsc: Args: [ '-c', 'tsc  --project tsconfig.json' ]
11 silly lifecycle test-ts-express-decorator@1.0.0~tsc: Returned: code: 2  signal: null
12 info lifecycle test-ts-express-decorator@1.0.0~tsc: Failed to exec tsc script
13 verbose stack Error: test-ts-express-decorator@1.0.0 tsc: `tsc  --project tsconfig.json`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid test-ts-express-decorator@1.0.0
15 verbose cwd /Users/Tyler/Projects/ts-decorators-example
16 verbose Darwin 16.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error test-ts-express-decorator@1.0.0 tsc: `tsc  --project tsconfig.json`
22 error Exit status 2
23 error Failed at the test-ts-express-decorator@1.0.0 tsc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by Romakita** [comment]
Hi @therealTP,
Sorry for this bug. I've found a bad import in the AjvService.
It's fixed in v1.14.2 ;)

See you

**Comment by therealTP** [comment]
Thank you Romain, you're awesome! When can we expect 2.14.2 to be available? I love this project, keep up the great work. 👏

**Comment by Romakita** [comment]
Hi @therealTP
It’s already available ;)

**Comment by therealTP** [comment]
Awesome, works like a charm. Thanks again!
