### ISSUE TITLE
3.4.0 description class decorator error

### ISSUE THREAD

**Issue by lwallent** [Romakita/ts-express-decorators#208]
I have updated to the latest release (3.4.0), however the Server will not start.

It seems to die on swagger class description decorator:

````typescript
@Controller("/assets")
@Description("The assets service") // <---------------
export class AssetsCtrl {
````

## Stacktrace

```
TypeError: Cannot read property 'merge' of undefined
    at Schema.decoratorSchemaFactory_1.decoratorSchemaFactory (/[REMOVED]/node_modules/ts-express-decorators/src/jsonschema/decorators/schema.ts:43:15)
    at parameters (/[REMOVED]/node_modules/ts-express-decorators/src/jsonschema/utils/decoratorSchemaFactory.ts:25:24)
    at Description.args (/[REMOVED]/node_modules/ts-express-decorators/src/swagger/decorators/description.ts:64:38)
    at DecorateConstructor (/[REMOVED]/node_modules/reflect-metadata/Reflect.ts:1090:31)
    at Object.decorate (/[REMOVED]/node_modules/reflect-metadata/Reflect.ts:284:20)
    at Object.__decorate (/[REMOVED]/node_modules/tslib/tslib.js:87:96)
    at Object.<anonymous> (/[REMOVED]/controllers/AssetsCtrl.ts:18:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Promise.resolve.then (/[REMOVED]/node_modules/ts-express-decorators/src/server/components/ServerLoader.ts:382:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
````

Type | Version
---|---
Bug | 3.4.0

Sorry, I do have not have time to investigate further right now. I have rolled back to 3.3.0 where it is working.

KR

Lasse

**Comment by Romakita** [comment]
Shit... I've missed this part. I'll fixed that.

**Comment by Romakita** [comment]
Fixed :)

**Comment by Romakita** [comment]
3.4.1
