### ISSUE TITLE
Error after inject a Service into a Controller

### ISSUE THREAD

**Issue by sinner** [Romakita/ts-express-decorators#237]
## Informations

Type | Version
Bug  | 3.9.2   

****

## Description
I'm having this error when I try to create a new service and I try to pass it through my Controller using IoC.

```sh
TypeError: Cannot read property 'service' of undefined
    at ParamRegistry.getParams.findIndex (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/filters/registries/ParamRegistry.ts:178:33)
    at Array.findIndex (native)
    at Function.ParamRegistry.hasNextFunction (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/filters/registries/ParamRegistry.ts:178:14)
    at HandlerMetadata.resolve (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/mvc/class/HandlerMetadata.ts:64:48)
    at new HandlerMetadata (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/mvc/class/HandlerMetadata.ts:38:14)
    at Function.from (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/mvc/class/HandlerBuilder.ts:35:39)
    at middlewares.concat.concat.concat.concat.concat.filter.map (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/mvc/class/EndpointBuilder.ts:62:54)
    at Array.map (<anonymous>)
    at EndpointBuilder.build (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/mvc/class/EndpointBuilder.ts:62:14)
    at ctrl.endpoints.forEach.endpoint (/var/www/javascript/MyProject/node_modules/ts-express-decorators/src/mvc/class/ControllerBuilder.ts:33:65)
(node:4134) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'service' of undefined
(node:4134) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Todos

My Server File:
```typescript
import * as Fs from "fs";
import * as Path from "path";
import "reflect-metadata";
import "ts-express-decorators/swagger";
import {getConnection} from "typeorm";
import {ServerLoader, ServerSettings, GlobalAcceptMimesMiddleware} from "ts-express-decorators";

const rootDir = Path.resolve(__dirname+'/..');
const sslKeyFile = Fs.readFileSync(
    Path.resolve(process.cwd()+'/'+process.env.SSL_KEY)
);
const sslCertFile = Fs.readFileSync(
    Path.resolve(process.cwd()+'/'+process.env.SSL_CERT)
);
const sslPassPhrase = process.env.SSL_PASSPHRASE;
const httpPort = process.env.HTTP_PORT;
const httpsPort = process.env.HTTPS_PORT;

@ServerSettings({
    rootDir,
    acceptMimes: ["application/json"],
    debug: false,
    httpPort,
    httpsPort,
    httpsOptions: {
        key: sslKeyFile,
        cert: sslCertFile,
        passphrase: sslPassPhrase
    },
    swagger: {
        path: "/api-docs"
    },
    mount: {
        "/api": `${rootDir}/controllers/api/**/*.ts`
    },
    componentsScan: [
        `${rootDir}/middlewares/**/*.ts`,
        `${rootDir}/services/**/*.ts`,
        `${rootDir}/converters/**/*.ts`
    ],
    customServiceOptions: {}
})
export class Server extends ServerLoader {

    constructor(private processEnv: any, public connection: any) {
        super();
    }

    /**
     * This method let you configure the middleware required by your application to works.
     * @returns {Server}
     */
    public $onMountingMiddlewares(): void|Promise<any> {

        const cookieParser = require('cookie-parser'),
            bodyParser = require('body-parser'),
            compress = require('compression'),
            methodOverride = require('method-override');

        let RateLimit = require('express-rate-limit');

        let apiLimiter = new RateLimit({
            windowMs: 15*60*1000, // 15 minutes
            max: 100,
            delayAfter: 50, // begin slowing down responses after the first request / 0 = disabled
            delayMs: 500, // slow down subsequent responses by 3 seconds per request / 0 = disabled
            message: "Too many requests, please try again later."
        });

        this.use(GlobalAcceptMimesMiddleware)
            .use(cookieParser())
            .use(compress({}))
            .use(methodOverride())
            .use(bodyParser.json())
            .use(bodyParser.urlencoded({extended: true}))
            .use('/api/', apiLimiter);

        return null;
    }

    public $onReady(){
        console.log(`Server started...`);
    }

    public $onServerInitError(err){
        console.error(err);
    }

}

```

My Service:
```typescript
import {Service} from "ts-express-decorators";
import {UserSignUpInterface} from "../interfaces/UserSignUpInterface";
import {UserRepository} from "../entity/repository/UserRepository";
import {APIResponseInterface} from "../interfaces/APIResponseInterface";
import {getCustomRepository} from "typeorm";

@Service()
export class UserService {

    private userRepository: UserRepository;
    private result: APIResponseInterface;

    constructor () {
        this.userRepository = getCustomRepository(UserRepository);
    }

    signupSimpleUser (userData: UserSignUpInterface) {
        userData.roles = ['ROLE_USER'];
        userData.isActive = 0;

        this.result.status = 500;
        this.result.error = {
            detail: 'It has occurred an unexpected error during the sign-up process. Refresh the page a try it again.'
        };
        this.result.data = {
            user: userData,
            success: false
        };
        this.result.message = 'It has occurred an unexpected error during the sign-up process. Refresh the page a try it again.';

        try {

            let newUser = this.userRepository.createUser(userData);
            this.result.error = null;
            this.result.data = {
                user: newUser,
                success: true
            };
            this.result.message = 'The sign-up process was completed successfully. An email was sent to confirm you registration.';
            this.result.status = 201;

            //TODO: Throw an event that will send an email to complete the user signed-up verification

        }
        catch (e) {
            console.log(e);
            this.result.status = 400;
            this.result.error = {
                detail: e
            };
            this.result.message = 'It has occurred an error during the sign-up process.';
        }
        return this.result;
    }

}
```

My Controller:
```typescript

@Controller("/user")
export class UserManagementCtrl {

    constructor (private userService: UserService) {
    }

    @Post("/sign-up")
    @Title("Sign up process for simple users")
    @Summary("Sign up process for simple users")
    @Description("This endpoint will manage the process to start with a sign-up process")
    @Status(201)
    async signUpAction(
        request: Express.Request,
        response: Express.Response,
        @BodyParams("user") userData: UserSignUpInterface): Promise<APIResponseInterface> {

        let result: APIResponseInterface = this.userService.signupSimpleUser(userData);
        response.setHeader('status', result.status);
        return result;

    }

}
```

**Comment by sinner** [comment]
Thank you very much in advance

**Comment by Romakita** [comment]
Hi @sinner ,

The problem is on your signUpAction. When you use a decorator on parameters, you need to use decorators for all parameters.

This right code is this:
```typescript
@Controller("/user")
export class UserManagementCtrl {

    constructor (private userService: UserService) {
    }

    @Post("/sign-up")
    @Title("Sign up process for simple users")
    @Summary("Sign up process for simple users")
    @Description("This endpoint will manage the process to start with a sign-up process")
    @Status(201)
    async signUpAction(
        @Req() request: Express.Request,
        @Res() response: Express.Response,
        @BodyParams("user") userData: UserSignUpInterface): Promise<APIResponseInterface> {

        let result: APIResponseInterface = this.userService.signupSimpleUser(userData);
        response.setHeader('status', result.status);
        return result;

    }
}
```
Just add `@Req() and @Res()` decorator ;)

See you
Romain

**Comment by sinner** [comment]
Sorry, I didn't know it. You are the best! Thank you very much.
