### ISSUE TITLE
Server don't provide a way to exclude files

### ISSUE THREAD

**Issue by myfingersarebroken** [Romakita/ts-express-decorators#253]
## Informations

Version
4.0.5

****

## Description
I like to maintain my .spec.ts in the same folder of the controller or service implementation, however Ts.ED don't provide a way to exclude this files from the server start up.
I don't know if it's a lack of feature or documentation.
I use jasmine-ts as my test suite.

Here the application log:

```bash
[2018-02-23T13:10:39.538] [INFO ] [TSED] - Scan files : /Users/fernando/ativa/git/api-conta-corrente/src/controllers/v1/**/*.ts
[2018-02-23T13:10:39.541] [INFO ] [TSED] - Scan files : /Users/fernando/ativa/git/api-conta-corrente/src/mvc/**/*.ts
[2018-02-23T13:10:39.547] [INFO ] [TSED] - Scan files : /Users/fernando/ativa/git/api-conta-corrente/src/services/**/*.ts
[2018-02-23T13:10:39.547] [INFO ] [TSED] - Scan files : /Users/fernando/ativa/git/api-conta-corrente/src/converters/**/*.ts
ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/fernando/ativa/git/api-conta-corrente/src/services/withdraw/withdraw.service.spec.ts:5:1)
    at Module._compile (module.js:635:30)
    at Module.m._compile (/Users/fernando/.nvm/versions/node/v8.9.3/lib/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/fernando/.nvm/versions/node/v8.9.3/lib/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
(node:57632) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: describe is not defined
(node:57632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by myfingersarebroken** [comment]
I studied the implementation and have concluded that I't would be awesome to have vinyl-fs as the fiel system adapter.

**Comment by Romakita** [comment]
Tel me if you need some informations :)
