### ISSUE TITLE
GlobalErrorHandlerMiddleware cannot be invoked without 'new' 

### ISSUE THREAD

**Issue by virus2016** [Romakita/ts-express-decorators#258]
## Informations

Type | Version
Bug | 4.0.7

****

## Description
Hey @Romakita! 

I am trying to use the GlobalErrorHandlerMiddleware for handling the global errors however I keep getting an exception below: 

```
TypeError: Class constructor $onGlobalError cannot be invoked without 'new' 
"TypeError: Class constructor $onGlobalError cannot be invoked without 'new'
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/src/node_modules/express/lib/router/index.js:317:13)
    at /src/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/src/node_modules/express/lib/router/index.js:335:12)
    at next (/src/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/src/node_modules/express/lib/router/index.js:317:13)
    at /src/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/src/node_modules/express/lib/router/index.js:335:12)
    at next (/src/node_modules/express/lib/router/index.js:275:10)"
```

My global handler looks like this: 

```javascript
import * as Express from 'express';
import { OverrideMiddleware, GlobalErrorHandlerMiddleware, Err, Req, Res } from '@tsed/common';

@OverrideMiddleware(GlobalErrorHandlerMiddleware)
export class $onGlobalError {

    use(@Err() error: any,
        @Req() request: Express.Request,
        @Res() response: Express.Response): any {

        if (error.status) {
            request.log.error({
                error: {
                    message: error.message,
                    stack: error.stack,
                    status: error.status
                }
            });
            response.status(error.status).send(error);
            return;
        }

        if (typeof error === 'string') {
            response.status(404).send(error);
            return;
        }

        request.log.error({
            error: {
                status: 500,
                message: error.message,
                stack: error.stack
            }
        });
        response.status(error.status || 500).json({
        });

        return;
    }
}
```

My Server (app.ts) looks like this: 

```javascript
import * as bodyParser from 'body-parser';
import * as compression from 'compression';
import * as cookieParser from 'cookie-parser';
import * as cors from 'cors';
import * as Express from 'express';
import { AppConfig } from './config/app.config';
import { GlobalAcceptMimesMiddleware, ServerLoader, ServerSettings } from '@tsed/common';
import '@tsed/ajv';
import { $onError } from './middleware/error/error.middleware';
import { $onGlobalError } from './middleware/error/globalerror.middleware';

let settings = {
    rootDir: AppConfig.rootDir,
    componentsScan: AppConfig.componentsScan,
    port: AppConfig.appPort,
    httpsPort: 0,
    endpointUrl: AppConfig.endpointUrl,
    acceptMimes: AppConfig.acceptMimes,
    swagger: AppConfig.swagger,
    version: AppConfig.version,
    ajv: {
        errorFormat: (error) => `At ${error.modelName}${error.dataPath}, value '${error.data}' ${error.message}`,
        options: { verbose: true }
    },
};

@ServerSettings(settings)
export class Server extends ServerLoader {

    $onMountingMiddlewares() {
        let origins = { origin: '*' };
        this.use(cors(origins));
        this.use(compression());
        this.use(GlobalAcceptMimesMiddleware);
        this.use(cookieParser());
        this.use(bodyParser.json());
        this.use(bodyParser.urlencoded({ extended: true }));
    }

    $afterRoutesInit() {
        this.use($onError);
        this.use($onGlobalError); // EDIT: Remove this line :)
    }

    $onServerInitError(err) {
        console.error(err);
    }

    $onReady() {

    }
}

```

I'm sure it's something I am doing..

Many thanks again,

**Comment by Romakita** [comment]
Hello @virus2016 ,

If you use the @OverrideMiddleware decorator, you don't need to add your middleware on $afterRoutesInit ;)

See you,
Romain

**Comment by virus2016** [comment]
Romain, it was my fault! We had a middleware folder, component scan was set to middlewares... 

Keep up the great work!

**Comment by Romakita** [comment]
Thanks @virus2016  :)
