### ISSUE TITLE
controllerScope Error

### ISSUE THREAD

**Issue by harlenalvarez** [Romakita/ts-express-decorators#287]
Hey @Romakita thanks for adding the feature to default the scope that was quick 👍 . 
However, when I set the default to REQUESTS I get a build error.
Is there something I am missing or not doing right?

Note: The application builds fine with the setting set to singleton.

## Informations

Type | Version
---|---
Bug | 4.10.0

****

## Description
Getting build error when defaulting the scope to REQUEST

These are my server settings
```typescript
@ServerSettings({
    mount: { '/api': '${rootDir}/dist/controllers/**/*.js'},
    port: 3000,
    acceptMimes: ['application/json'],
    componentsScan: [
        '${rootDir}/dist/extensions/middlewares/**/*.js',
        '${rootDir}/dist/services/**/*.js'
    ],
    validationModelStrict: true,
    controllerScope: ProviderScope.REQUEST
})
```

Error it throws
```
TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at Object.descriptorOf (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\core\utils\index.ts:320:19)
    at Inject (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\decorators\inject.ts:27:30)
    at new ExpressApplication (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\mvc\decorators\class\expressApplication.ts:53:38)
    at Function.invoke (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:277:16)
    at designParamTypes.map (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:271:33)
    at Array.map (<anonymous>)
    at Function.invoke (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:243:14)
    at registry.forEach.provider (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:359:53)
    at Map.forEach (<anonymous>)
    at Registry.forEach (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\core\class\Registry.ts:140:19)
    at Function.buildRegistry (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:357:18)
    at Function.<anonymous> (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:443:14)
    at Generator.next (<anonymous>)
    at C:\Users\halvarez007\Source\IrtApi\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\halvarez007\Source\IrtApi\node_modules\tslib\tslib.js:103:16)
    at Function.load (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\common\lib\di\services\InjectorService.js:350:24)
    at InjectorService.<anonymous> (C:\Users\halvarez007\Source\IrtApi\node_modules\@tsed\src\common\di\services\InjectorService.ts:209:32)
    at Generator.next (<anonymous>)
    at C:\Users\halvarez007\Source\IrtApi\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
(node:14392) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot convert undefined or null to object
(node:14392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is my package.json
```
{
  "name": "irtapi",
  "version": "1.1.0",
  "description": "Generated by Dessert CLI",
  "main": "app.js",
  "scripts": {
    "clean": "rimraf \"./dist\"",
    "build": "npm run clean && \"node_modules/.bin/tsc\" --project ./src/tsconfig.app.json",
    "start": "npm run serve",
    "server": "node ./dist/app.js",
    "serve": "npm run build && npm run server",
    "coverage": "npm run test-cov && npm run test-remap",
    "test": "node_modules/.bin/mocha -r ts-node/register --recursive \"./src/**/*.spec.ts\"",
    "e2e": "npm run build && \"node_modules/.bin/mocha\" -r ts-node/register --recursive \"./e2e/**/*.spec.ts\"",
    "tslint": "node_modules/.bin/tslint ./src/**/*.ts",
    "watch:serve": "node_modules/.bin/tsc-watch --project ./src/tsconfig.app.json --onSuccess \"node ./dist/app.js\"",
    "watch:test": "node_modules/.bin/mocha -r ts-node/register --watch --recursive \"./src/**/*.spec.ts\" --watch-extensions ts"
  },
  "keywords": [
    "node api"
  ]
  "dependencies": {
    "@pa-util/idam-openidauth": "^0.2.5",
    "@tsed/ajv": "4.10.0",
    "@tsed/common": "4.10.0",
    "@tsed/core": "4.10.0",
    "@tsed/testing": "4.10.0",
    "ajv": "6.2.1",
    "compression": "1.7.2",
    "cors": "^2.8.4",
    "express": "4.16.3",
    "morgan": "1.9.0",
    "mssql": "4.1.0",
    "reflect-metadata": "^0.1.12",
    "ts-express-decorators": "4.10.0",
    "ts-httpexceptions": "3.0.2",
    "typeorm": "0.1.16",
    "xlsx": "^0.12.4"
  },
  "devDependencies": {
    "@types/chai": "^4.1.1",
    "@types/compression": "^0.0.35",
    "@types/cors": "^2.8.3",
    "@types/express": "4.11.1",
    "@types/mocha": "^2.2.48",
    "@types/morgan": "^1.7.35",
    "@types/node": "^9.4.6",
    "@types/sinon": "^4.3.0",
    "@types/supertest": "^2.0.4",
    "chai": "^4.1.2",
    "mocha": "^5.0.1",
    "node-mocks-http": "^1.6.7",
    "rimraf": "^2.6.2",
    "sinon": "^4.4.2",
    "supertest": "^3.0.0",
    "ts-node": "5.0.1",
    "tsc-watch": "1.0.16",
    "tslint": "^5.9.1",
    "typemoq": "^2.1.0",
    "typescript": "2.7.2"
  }
}
```

**Comment by Romakita** [comment]
Fixed :) v4.10.2
