### ISSUE TITLE
[Bug] Service initialization error

### ISSUE THREAD

**Issue by yangukmo** [Romakita/ts-express-decorators#334]
## Informations

Type | Version
---|---
Bug | 4.17.3

****

## Description

Hi, @Romakita 
A very critical error has occurred...
```
TypeError: Cannot use 'in' operator to search for '$onInit' in undefined
     at ProviderRegistry_1.GlobalProviders.forEach (/Users/ukmo/github/vitamin/node_modules/@tsed/src/common/di/services/InjectorService.ts:343:26)
     at Map.forEach (<anonymous>)
     at Providers.forEach (/Users/ukmo/github/vitamin/node_modules/@tsed/src/core/class/Registry.ts:167:19)
     at Function.<anonymous> (/Users/ukmo/github/vitamin/node_modules/@tsed/src/common/di/services/InjectorService.ts:340:25)
     at Generator.next (<anonymous>)
     at /Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (/Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:103:16)
     at Function.emit (/Users/ukmo/github/vitamin/node_modules/@tsed/common/lib/di/services/InjectorService.js:274:24)
     at Function.<anonymous> (/Users/ukmo/github/vitamin/node_modules/@tsed/src/common/di/services/InjectorService.ts:472:18)
     at Generator.next (<anonymous>)
     at /Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (/Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:103:16)
     at Function.load (/Users/ukmo/github/vitamin/node_modules/@tsed/common/lib/di/services/InjectorService.js:363:24)
     at InjectorService.<anonymous> (/Users/ukmo/github/vitamin/node_modules/@tsed/src/common/di/services/InjectorService.ts:217:32)
     at Generator.next (<anonymous>)
     at /Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (/Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:103:16)
     at InjectorService.load (/Users/ukmo/github/vitamin/node_modules/@tsed/common/lib/di/services/InjectorService.js:172:24)
     at Server.<anonymous> (/Users/ukmo/github/vitamin/node_modules/@tsed/src/common/server/components/ServerLoader.ts:213:37)
     at Generator.next (<anonymous>)
     at /Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (/Users/ukmo/github/vitamin/node_modules/tslib/tslib.js:103:16)
     at Server.loadSettingsAndInjector (/Users/ukmo/github/vitamin/node_modules/@tsed/common/lib/server/components/ServerLoader.js:185:24)
     at Server.<anonymous> (/Users/ukmo/github/vitamin/node_modules/@tsed/src/common/server/components/ServerLoader.ts:249:24)
```
This error occurs in version 4.17.3.

Our service has been a big incident, and now it has been forced downgraded...

## Todos

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by vincent178** [comment]
Hi @yangukmo, can you please provide a minimal reproducible code?

**Comment by Romakita** [comment]
@yangukmo The fix is ready. Release will be available soon.

But, the problem come from at least a service/factory isn't initialized correctly. So it's possible after updating the `@tsed/common` package that you have another problem.

Tell me if the you have another bug ;)

See you,
Romain
