### ISSUE TITLE
Circular dependency error with @Ref decorator

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#340]
the following throw an error:

```ts
@Model({})
export class Product {
    @Ref(Variant)
    variants: Variant[]
}
@Model({})
export class Variant {
    @Ref(Product)
    product: Product
}
```

```bash
[2018-04-26T16:41:01.297] [ERROR] [TSED] - TypeError: Cannot read property 'prototype' of undefined
```

**Comment by Romakita** [comment]
Circular dependency is a bad pattern XD, no?

**Comment by milewski** [comment]
not always.. specially when it is regarding to database instead of having a pivot table like this:

```
products ->
   variants -> ObjectID[]

variants -> 
   ....

product_variant -> 
   product_id -> ObjectID
   variant_id -> ObjectID
```

a `HasMany / BelongsTo` type of relationship might be the ideal solution in many cases... 

```
product ->
   variants -> ObjectID[]

variants -> 
  product_id -> ObjectID[]
```

**Comment by Romakita** [comment]
Ok I understand, but a class cannot be used before is declaration in ES6. So the only way is to use the string name of the class like this:

```typescript
@Model({})
export class Product {
    @Ref("Variant")
    variants: Variant[]
}
@Model({})
export class Variant {
    @Ref(Product)
    product: Product
}
```
This feature isn't implemented currently. But I can patch the decorator ASAP.

**Comment by Romakita** [comment]
PR ready https://github.com/Romakita/ts-express-decorators/pull/343/files

**Comment by milewski** [comment]
testing this PR i get an error

```
{ INJECTION_ERROR: Service RoleService > Role not found.
    at Function.mapServices (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:286:19)
    at designParamTypes.map (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:257:22)
    at Array.map (<anonymous>)
......
```

and the file it is referring to import role like this

```ts
@Service()
export class RoleService {

    constructor(@Inject(Role) private model: MongooseModel<Role>) {}

}
```

**Comment by Romakita** [comment]
Reopen. Error when github has closed this issue instead of #348  (my bad).

**Comment by troyanskiy** [comment]
Does someone work on the issue?
I can put my eye on it since I will need that in my models.

**Comment by Romakita** [comment]
I work on ;)
