### ISSUE TITLE
[Question] Two services try to use each other's functions.

### ISSUE THREAD

**Issue by yangukmo** [Romakita/ts-express-decorators#374]
## Informations

Type | Version
---|---
Question | 4.18.0

****

## Description
Hi, @Romakita 
My question may be stupid..
Two services try to use each other's functions.
```javascript
// A.ts
import {B} from 'B'
@Service()
export class A {
  constructor(b: B) {}
  func1() {...}
  func2() {
    b.func3()
  }
}

// B.ts
import {A} from 'A'
@Service()
export class B {
  constructor(a: A) {}
  func3() {...}
  func4() {
    a.func1()
  }
}

```

Running the sample code above will cause an error.
Is there a way to use it like the sample code?
```
TypeError: Cannot read property 'prototype' of undefined
     at getClass (.../node_modules/@tsed/src/core/utils/index.ts:20:17)
     at Object.getClassOrSymbol (.../node_modules/@tsed/src/core/utils/index.ts:29:48)
     at Providers.get (.../node_modules/@tsed/src/core/class/Registry.ts:55:26)
     at Function.mapServices (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:281:38)
     at designParamTypes.map.serviceType (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:255:12)
     at Array.map (<anonymous>)
     at Function.invoke (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:254:39)
     at container.forEach.provider (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:489:36)
     at Map.forEach (<anonymous>)
     at Function.build (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:476:15)
     at Function.<anonymous> (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:464:10)
     at Generator.next (<anonymous>)
     at .../node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (.../node_modules/tslib/tslib.js:103:16)
     at Function.load (.../node_modules/@tsed/common/lib/di/services/InjectorService.js:360:24)
     at InjectorService.<anonymous> (.../node_modules/@tsed/src/common/di/services/InjectorService.ts:211:28)
     at Generator.next (<anonymous>)
     at .../node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (.../node_modules/tslib/tslib.js:103:16)
     at InjectorService.load (.../node_modules/@tsed/common/lib/di/services/InjectorService.js:172:24)
     at Server.<anonymous> (.../node_modules/@tsed/src/common/server/components/ServerLoader.ts:212:33)
     at Generator.next (<anonymous>)
     at .../node_modules/tslib/tslib.js:107:75
     at new Promise (<anonymous>)
     at Object.__awaiter (.../node_modules/tslib/tslib.js:103:16)
     at Server.loadSettingsAndInjector (.../node_modules/@tsed/common/lib/server/components/ServerLoader.js:185:24)
```

**Comment by yangukmo** [comment]
This code is wrong. (Circular dependencies)
I'm sorry :(
