### ISSUE TITLE
Error with bootstrap method: error TS2554: Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#383]
The following code is no longer working after `4.19.0`

```ts
import { bootstrap } from '@tsed/testing'
import { Server } from '../Server'

bootstrap(Server)(async () => {
    console.log('works')
})
```

i get the following typescript error: 

```
error TS2554: Expected 0 arguments, but got 1.
```

**Comment by Romakita** [comment]
Yep, Now the bootstrap function return a Promise. Do you want a fix ?

**Comment by milewski** [comment]
Im fine with a promise :) let me try

**Comment by Romakita** [comment]
```typescript
bootstrap(Server)().then(() => {

})
```
I think the code is a bit longer and confusing XD. But if you wrap this code like that:

```typescript
async function bootstrapServer() { 
    await bootstrap(Server)();
    // ...
}
```
If is not understandable, we can provide another way to write the code properly.

See you,
Romain

**Comment by milewski** [comment]
i still cant get this to work.... looking the source code you are checking for `after` which only exists in mocha context... im getting this error:

```
/Users/milewski/Code/yumi-frontend/backend/node_modules/@tsed/src/testing/bootstrap.ts:16
  if (after) {
  ^
ReferenceError: after is not defined
    at Object.bootstrap (/Users/milewski/Code/yumi-frontend/backend/node_modules/@tsed/src/testing/bootstrap.ts:16:3)
    at Object.<anonymous> (/Users/milewski/Code/yumi-frontend/backend/source/database/Command.ts:8:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module.m._compile (/Users/milewski/Code/yumi-frontend/backend/node_modules/ts-node/src/index.ts:430:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/milewski/Code/yumi-frontend/backend/node_modules/ts-node/src/index.ts:433:12)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at Object.<anonymous> (/Users/milewski/Code/yumi-frontend/backend/node_modules/ts-node/src/bin.ts:147:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)

```

**Comment by Romakita** [comment]
Ok I've restored bootstrap with done parameters, because promise isn't supported for all version of mocha / other test lib, and I removed the after calling (not necessary).

**Comment by milewski** [comment]
new error after upgrade:

```
/Users/milewski/Code/yumi-frontend/backend/node_modules/@tsed/src/testing/bootstrap.ts:22
    this.$$injector = instance.injector;
                   ^
TypeError: Cannot set property '$$injector' of undefined

```

**Comment by Romakita** [comment]
Well, it's problematic because I need a this context to store the current injector for all tests in the same "describe" unit test.

If you use the `@tsed/testing` for your own tools, it would be preferable to create your own bootstrap function, no ? 
You just need that:

```typescript
function bootstrap (){
    $log.stop();
    process.env.NODE_ENV = process.env.NODE_ENV || "test";
  
    const instance = new server(...args);

    // remove startServers methods to avoid the listening port
    instance.startServers = () => Promise.resolve();
   return instance.start();
}
```

**Comment by milewski** [comment]
i did try going that route, however i always had an error with that InjectorService which i had no idea why..  for example:

```
const instance = new Server()
instance[ 'startServers' ] = () => Promise.resolve()

instance.start().then(async () => {

    try{
        InjectorService.get<MongooseService>(MongooseService)
    } catch (e) {
        console.log(InjectorService) <-- '[Function: InjectorService]'
        console.log(e) <-- 'Cannot read property 'get' of undefined'
    }

})
```

**Comment by milewski** [comment]
never-mind i just saw that `instance` also provides a `instance.injector` using that one it works :D

**Comment by Romakita** [comment]
Yes, because now, server create a new instance of injector (containerization). So the InjectorService.get is not loaded. It's a breaking change, but I don't finish the work about the container. 
So in my side I'll fix this problem to stay compatible with the previous version. But in future the static method `InjectorService.get` will be deprecated.
For your code, the fix is that:

```
const instance = new Server()
instance[ 'startServers' ] = () => Promise.resolve()

instance.start().then(async () => {

    try{
        instance.injector.get<MongooseService>(MongooseService)
    } catch (e) {
        console.log(InjectorService) <-- '[Function: InjectorService]'
        console.log(e) <-- 'Cannot read property 'get' of undefined'
    }

})
```

**Comment by Romakita** [comment]
the fix is ready :)
