### ISSUE TITLE
[bug] SocketUseAfter throws an error

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#393]
Hi,
When I append `@SocketUseAfter()` (error handler) to SockeService  then it throws mi an error on every request:

`TypeError: Cannot read property 'prototype' of undefined`

I didn't see it before.
Have you similar situation?
Without decorator everything works fine.

**Comment by Romakita** [comment]
Hum I don't know, I need to test it.

**Comment by angusmunro** [comment]
Hi @Romakita,

 I am having the same issue with the latest version (We haven't previously used **@SocketUseAfter()** ). 

I can confirm that same problem occurs with **@SocketUseBefore()** as well and on both functions and class decoration. It also seems to happen with both **@SocketMiddleware()** and **@SocketMiddlewareError()**

My example is mostly from your docs (which are great by the way, thanks so much!)

Middleware:
```
import { SocketMiddleware, Args } from '../../node_modules/@tsed/socketio';
import { ConverterService } from '../../node_modules/@tsed/common';

@SocketMiddleware()
export class UserConverterSocketMiddleware {
    constructor(private converterService: ConverterService) {
    }
    async use(@Args() args: any[]) {

        let [user] = args;
        // update Arguments
        user = 'true';

        return [user];
    }
}
```

Service:
```
import { SocketService, SocketUseAfter, SocketUseBefore, Emit, Input, Args } from '@tsed/socketio';
import { UserConverterSocketMiddleware } from '../../middlewares/socket.auth.middleware';

@SocketService('/my-namespace')
@SocketUseBefore(UserConverterSocketMiddleware) // global version
export class MySocketService {

    @Input('eventName')
    @Emit('responseEventName') // or Broadcast or BroadcastOthers
    @SocketUseBefore(UserConverterSocketMiddleware)
    async myMethod(@Args(0) user: any) {

        console.log(user);

        return user;
    }
}
```

Error:
```
(node:571) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'prototype' of undefined
    at Object.getClass (/usr/src/app/node_modules/@tsed/src/core/utils/ObjectUtils.ts:13:17)
    at Function.hasOwn (/usr/src/app/node_modules/@tsed/src/core/class/Metadata.ts:293:40)
    at Store._storeGet (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:214:19)
    at Store._map (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:35:23)
    at new Store (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:37:7)
    at Function.from (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:54:12)
    at SocketHandlersBuilder.bindMiddleware (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:240:62)
    at SocketHandlersBuilder.<anonymous> (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:156:24)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:103:16)
    at useBefore.forEach (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:155:40)
    at Array.forEach (<anonymous>)
    at SocketHandlersBuilder.<anonymous> (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:155:17)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:103:16)
    at SocketHandlersBuilder.runQueue (/usr/src/app/node_modules/@tsed/socketio/lib/class/SocketHandlersBuilder.js:117:24)
    at Socket.socket.on.args (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:128:18)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /usr/src/app/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:571) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Versions used:
```
    "@tsed/ajv": "4.29.0",
    "@tsed/common": "4.29.0",
    "@tsed/core": "4.29.0",
    "@tsed/mongoose": "4.29.0",
    "@tsed/socketio": "^4.29.0",
    "@tsed/swagger": "4.29.0",
    "@tsed/testing": "4.29.0",
```

I'll look into this a bit more tomorrow and report back here if I find anything out, currently playing around with authentication on web sockets and these middleware would be perfect :-)

Thanks as always!

**Comment by Romakita** [comment]
@angusmunro Thanks I'll fix that ASAP. And sorry if I reply lately.

**Comment by Romakita** [comment]
@kalu111 @angusmunro It's fixed ^^. v4.29.1

**Comment by angusmunro** [comment]
Hi Romakita,

I'm still seeing the same issue on version 4.29.1, with the same code I had above.

```
(node:157) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'prototype' of undefined
    at Object.getClass (/usr/src/app/node_modules/@tsed/src/core/utils/ObjectUtils.ts:13:17)
    at Function.hasOwn (/usr/src/app/node_modules/@tsed/src/core/class/Metadata.ts:293:40)
    at Store._storeGet (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:214:19)
    at Store._map (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:35:23)
    at new Store (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:37:7)
    at Function.from (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:54:12)
    at SocketHandlersBuilder.bindMiddleware (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:240:62)
    at handlerMetadata.useBefore.forEach.target (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:161:67)
    at Array.forEach (<anonymous>)
    at SocketHandlersBuilder.<anonymous> (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:161:33)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:103:16)
    at SocketHandlersBuilder.runQueue (/usr/src/app/node_modules/@tsed/socketio/lib/class/SocketHandlersBuilder.js:117:24)
    at Socket.socket.on.args (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:128:18)
(node:157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:157) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:157) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'prototype' of undefined
    at Object.getClass (/usr/src/app/node_modules/@tsed/src/core/utils/ObjectUtils.ts:13:17)
    at Function.hasOwn (/usr/src/app/node_modules/@tsed/src/core/class/Metadata.ts:293:40)
    at Store._storeGet (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:214:19)
    at Store._map (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:35:23)
    at new Store (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:37:7)
    at Function.from (/usr/src/app/node_modules/@tsed/src/core/class/Store.ts:54:12)
    at SocketHandlersBuilder.bindMiddleware (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:240:62)
    at handlerMetadata.useBefore.forEach.target (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:161:67)
    at Array.forEach (<anonymous>)
    at SocketHandlersBuilder.<anonymous> (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:161:33)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:103:16)
    at SocketHandlersBuilder.runQueue (/usr/src/app/node_modules/@tsed/socketio/lib/class/SocketHandlersBuilder.js:117:24)
    at Socket.socket.on.args (/usr/src/app/node_modules/@tsed/src/socketio/class/SocketHandlersBuilder.ts:128:18)
(node:157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
