### ISSUE TITLE
SyntaxError: missing ) after argument list (in Linux machine)

### ISSUE THREAD

**Issue by islavi** [Romakita/ts-express-decorators#426]
## Informations
Getting error message when trying to run the server (on Linux machine, windows works ok):

```
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.register (/opt/app/lc/node_modules/ts-node/src/index.ts:227:26)
    at Object.<anonymous> (/opt/app/lc/node_modules/ts-node/src/bin.ts:103:17)
    at Module._compile (module.js:409:26)
```

**server.ts file:**
```
import { $log } from 'ts-log-debug';
import { Server } from './app';

new Server()
    .start()
    .then(() => {
        $log.info('Server started...');
    })
    .catch((err) => {
        $log.error(err);
    });
```

**app.ts (part of the file):**
```
const rootDir = Path.resolve(__dirname);
@ServerSettings({
    rootDir,
    mount: {
        '/v1': `${rootDir}/controllers/**/**.controller.{ts,js}`
    },
    componentsScan: [
        `${rootDir}/services/**/**.service.{ts,js}`,
        `${rootDir}/middlewares/**/**.{ts,js}`,
        `${rootDir}/dal/**/**.{ts,js}`
    ],
    httpPort: process.env.PORT || 3000,
    httpsPort: false,
    acceptMimes: ['application/json'],
    swagger: {
        path: '/api-docs'
    }
})
export class Server extends ServerLoader {

    corsOptions: cors.CorsOptions;
    collectorService: CollectorService;

    constructor() {
        super();
        this.initCORS();
    }
```

Type | Version
---|---
|4.29.1

## Acceptance criterias
Should work in Linux same as windows

**Comment by islavi** [comment]
I run the .ts file instead of the .js file from dist lib.
