### ISSUE TITLE
Problem with file upload using MultipartFile

### ISSUE THREAD

**Issue by AbhijitMitra** [Romakita/ts-express-decorators#427]
I am getting this when I am trying to upload a file using Postman:
```
[2018-08-03T20:47:01.095] [ERROR] [TSED] - {
  "error": {
    "status": 500,
    "message": "Multipart: Boundary not found",
    "stack": "Error: Multipart: Boundary not found\n    at new Multipart (D:\\Signet\\Signet_Temp\\node_modules\\busboy\\lib\\types\\multipart.js:58:11)\n    at Multipart (D:\\Signet\\Signet_Temp\\node_modules\\busboy\\lib\\types\\multipart.js:26:12)\n    at Busboy.parseHeaders (D:\\Signet\\Signet_Temp\\node_modules\\busboy\\lib\\main.js:71:22)\n    at new Busboy (D:\\Signet\\Signet_Temp\\node_modules\\busboy\\lib\\main.js:22:10)\n    at multerMiddleware (D:\\Signet\\Signet_Temp\\node_modules\\multer\\lib\\make-middleware.js:33:16)\n    at MultipartFileMiddleware.use (D:\\Signet\\Signet_Temp\\node_modules\\@tsed\\src\\multipartfiles\\middlewares\\MultipartFileMiddleware.ts:36:49)\n    at HandlerBuilder.<anonymous> (D:\\Signet\\Signet_Temp\\node_modules\\@tsed\\src\\common\\mvc\\class\\HandlerBuilder.ts:116:45)\n    at Generator.next (<anonymous>)\n    at D:\\Signet\\Signet_Temp\\node_modules\\tslib\\tslib.js:107:75\n    at new Promise (<anonymous>)"
  },
  "reqId": "23",
  "method": "POST",
  "url": "/rest/api/file",
  "duration": 1,
  "headers": {
    "host": "192.168.50.109:8000",
    "connection": "keep-alive",
    "content-length": "5188",
    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
    "cache-control": "no-cache",
    "origin": "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop",
    "postman-token": "18de75b1-3865-62a8-614c-a70ff1b9ac5e",
    "content-type": "multipart/form-data",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate",
    "accept-language": "en-US,en;q=0.9"
  },
  "body": {},
  "query": {},
  "params": {}
}
```

**Comment by Romakita** [comment]
Hi @AbhijitMitra ,

Can you send me your Controller and method declaration ?
See you
Romain

**Comment by AbhijitMitra** [comment]
Hi @Romakita 

Below is my controller and method. I am trying to upload a file using Postman. When I do that I get the above error. 
Am I doing anything wrong?

import {Controller, Post} from "@tsed/common";
import {MultipartFile, MulterOptions} from "@tsed/multipartfiles";
 
 
type MulterFile = Express.Multer.File[];
 
@Controller('/api')
export class MyCtrl {
    
  @Post('/file')
  async uploadFile(@MultipartFile("image", 1) file: MulterFile) {
 
  }
}

**Comment by Romakita** [comment]
Ok I'll try your example with Postman ;)

**Comment by Romakita** [comment]
Hi @AbhijitMitra,
Can you send me your postman configuration ?
