### ISSUE TITLE
TypeORM and TS.ed integration is not working

### ISSUE THREAD

**Issue by sinner** [Romakita/ts-express-decorators#442]
## Informations

Type | Version
---|---
Question or Error | 4.x

****

## Description
I'm doing an integration of TS.ed and TypeORM but I'm receiving an error after implementing that integration according to the [documentation](http://tsed.io/#/tutorials/typeorm).

The error is `ConnectionNotFoundError: Connection "default" was not found` as you can see on the following log:
```sh
MACs-MacBook-Pro:local jsinner$ docker exec -it project-api-node bash
root@133cd09eb3d4:/var/srv/app# su node
node@133cd09eb3d4:/var/srv/app$ npm start

> test-ts-express-decorator@1.0.0 start /var/srv/app
> nodemon --watch '**/*.ts' --ignore 'node_modules/**/*' --exec ts-node src/index.ts

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: **/*.ts
[nodemon] starting `ts-node src/index.ts`
Reading .env file from /var/srv/app/.env
Reading DB settings from file from /var/srv/app/ormconfig.json: 
 [object Object]
[2018-08-29T17:41:06.645] [INFO ] [TSED] - Scan files : /var/srv/app/src/controllers/current/**/*.ts
[2018-08-29T17:41:06.651] [INFO ] [TSED] - Scan files : /var/srv/app/src/controllers/v1/**/*.ts
[2018-08-29T17:41:06.653] [INFO ] [TSED] - Scan files : /var/srv/app/src/middlewares/**/*.ts
[2018-08-29T17:41:06.656] [INFO ] [TSED] - Scan files : /var/srv/app/src/services/**/*.ts
[2018-08-29T17:41:06.657] [INFO ] [TSED] - Scan files : /var/srv/app/src/converters/**/*.ts
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.rootDir => /var/srv/app
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.env => development
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.httpPort => 3080
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.httpsPort => 3090
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.version => 1.0.0
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.uploadDir => /var/srv/app/uploads
[2018-08-29T17:41:06.771] [INFO ] [TSED] - settings.debug => false
[2018-08-29T17:41:06.772] [INFO ] [TSED] - settings.logger => { logRequest: true }
[2018-08-29T17:41:06.774] [INFO ] [TSED] - settings.mount => { '/': '/var/srv/app/src/controllers/current/**/*.ts',
  '/v1': '/var/srv/app/src/controllers/v1/**/*.ts' }
[2018-08-29T17:41:06.774] [INFO ] [TSED] - settings.componentsScan => [ '/var/srv/app/src/middlewares/**/*.ts',
  '/var/srv/app/src/services/**/*.ts',
  '/var/srv/app/src/converters/**/*.ts' ]
[2018-08-29T17:41:06.775] [INFO ] [TSED] - settings.acceptMimes => [ 'application/json' ]
[2018-08-29T17:41:06.775] [INFO ] [TSED] - settings.httpsOptions => { key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 76 51 49 42 41 44 41 4e 42 67 6b 71 68 6b 69 47 39 77 ... >,
  cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 45 52 44 43 43 41 79 79 67 41 77 49 42 41 67 49 4a 41 50 ... >,
  passphrase: 'a6ff5a915c7d07c6f1b443d17af8d7c5ab3ed2d1',
  port: '3090' }
[2018-08-29T17:41:06.776] [INFO ] [TSED] - settings.typeorm => { db: 
   { name: 'default',
     type: 'postgres',
     host: 'project-db-postgresql',
     port: 5432,
     username: 'project',
     password: 'project',
     database: 'project',
     synchronize: true,
     logging: false,
     cache: { type: 'redis', options: [Object] },
     entities: [ 'src/entity/**/*.ts' ],
     migrations: [ 'src/entity/migrations/**/*.ts' ],
     subscribers: [ 'src/entity/subscribers/**/*.ts' ],
     cli: 
      { entitiesDir: 'src/entity',
        migrationsDir: 'src/entity/migrations',
        subscribersDir: 'src/entity/subscribers' } } }
[2018-08-29T17:41:06.776] [INFO ] [TSED] - settings.swagger => { path: '/api-docs' }
[2018-08-29T17:41:06.776] [INFO ] [TSED] - settings.customServiceOptions => {}
[2018-08-29T17:41:06.776] [INFO ] [TSED] - Build services
{ ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/var/srv/app/src/error/ConnectionNotFoundError.ts:8:9)
    at ConnectionManager.get (/var/srv/app/src/connection/ConnectionManager.ts:40:19)
    at Object.getCustomRepository (/var/srv/app/src/index.ts:286:35)
    at new UserService (/var/srv/app/src/services/UserService.ts:27:41)
    at Function.invoke (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:277:16)
    at registry.forEach.provider (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:359:53)
    at Map.forEach (<anonymous>)
    at Registry.forEach (/var/srv/app/node_modules/@tsed/src/core/class/Registry.ts:140:19)
    at Function.buildRegistry (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:357:18)
    at Function.<anonymous> (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:449:14)
  name: 'ConnectionNotFoundError',
  message: 'Connection "default" was not found.' }
(node:102) UnhandledPromiseRejectionWarning: ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/var/srv/app/src/error/ConnectionNotFoundError.ts:8:9)
    at ConnectionManager.get (/var/srv/app/src/connection/ConnectionManager.ts:40:19)
    at Object.getCustomRepository (/var/srv/app/src/index.ts:286:35)
    at new UserService (/var/srv/app/src/services/UserService.ts:27:41)
    at Function.invoke (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:277:16)
    at registry.forEach.provider (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:359:53)
    at Map.forEach (<anonymous>)
    at Registry.forEach (/var/srv/app/node_modules/@tsed/src/core/class/Registry.ts:140:19)
    at Function.buildRegistry (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:357:18)
    at Function.<anonymous> (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:449:14)
(node:102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] clean exit - waiting for changes before restart
```

This is my Server class with my configuration
```ts
import {ServerLoader, ServerSettings, GlobalAcceptMimesMiddleware} from "@tsed/common";
import { Connection } from 'typeorm';
import * as Fs from "fs";
import * as Path from "path";
import "reflect-metadata";
import "@tsed/swagger";
import "@tsed/typeorm";

const rootDir = Path.resolve(__dirname+'/../..');
const sourceDir = Path.resolve(__dirname+'/..');
const sslKeyFile = Fs.readFileSync(
    Path.resolve(process.cwd()+'/'+process.env.SSL_KEY)
);
const sslCertFile = Fs.readFileSync(
    Path.resolve(process.cwd()+'/'+process.env.SSL_CERT)
);

const sslPassPhrase = process.env.SSL_PASSPHRASE;
const httpPort = process.env.HTTP_PORT;
const httpsPort = process.env.HTTPS_PORT;

const dbSettingsPath = `${rootDir}/ormconfig.json`;
const databaseSettings = JSON.parse(Fs.readFileSync(dbSettingsPath, 'utf8'));

@ServerSettings({
    rootDir,
    acceptMimes: ["application/json"],
    debug: false,
    httpPort,
    httpsPort,
    httpsOptions: {
        key: sslKeyFile,
        cert: sslCertFile,
        passphrase: sslPassPhrase
    },
    typeorm: {
        'db': databaseSettings
    },
    swagger: {
        path: "/api-docs"
    },
    mount: {
        "/": `${sourceDir}/controllers/current/**/*.ts`,
        "/v1": `${sourceDir}/controllers/v1/**/*.ts`
    },
    componentsScan: [
        `${sourceDir}/middlewares/**/*.ts`,
        `${sourceDir}/services/**/*.ts`,
        `${sourceDir}/converters/**/*.ts`
    ],
    customServiceOptions: {}
})
export class Server extends ServerLoader {

    constructor(private processEnv: any) {
        super();
    }

    /**
     * This method let you configure the middleware required by your application to works.
     * @returns {Server}
     */
    public $onMountingMiddlewares(): void|Promise<any> {

        const cookieParser = require('cookie-parser'),
            bodyParser = require('body-parser'),
            compress = require('compression'),
            methodOverride = require('method-override');

        let RateLimit = require('express-rate-limit');

        let apiLimiter = new RateLimit({
            windowMs: 15*60*1000, // 15 minutes
            max: 100,
            message: "Too many requests, please try again later."
        });

        this.use(GlobalAcceptMimesMiddleware)
            .use(cookieParser())
            .use(compress({}))
            .use(methodOverride())
            .use(bodyParser.json())
            .use(bodyParser.urlencoded({extended: true}))
            .use('/api/', apiLimiter);

        return null;
    }

    public $onReady(){
        console.log(`Server started...`);
    }

    public $onServerInitError(err){
        console.error(err);
    }

}

```

The dabaseSettings variable is a json with this structure:
```json
{
   "name": "default",
   "type": "postgres",
   "host": "project-db-postgresql",
   "port": 5432,
   "username": "project",
   "password": "project",
   "database": "project",
   "synchronize": true,
   "logging": false,
   "cache": {
        "type": "redis",
        "options": {
            "host": "project-cache-redis",
            "port": 6379
        }
   },
   "entities": [
        "src/entity/**/*.ts"
   ],
   "migrations": [
        "src/entity/migrations/**/*.ts"
   ],
   "subscribers": [
        "src/entity/subscribers/**/*.ts"
   ],
   "cli": {
        "entitiesDir": "src/entity",
        "migrationsDir": "src/entity/migrations",
        "subscribersDir": "src/entity/subscribers"
   }
}
```

I think in the documentation is missing some comments because it looks like the Serve class is trying to get the connection and this connection is not created in no place.

So I've followed the TypeORM documentation and try to create this connection from the index.js file and doing some little changes on my Sever class wrapping the bootstrap process of the server into the promise of the conection creation process, and I'm receiving another error `AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.`:

```sh
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/index.ts`
Reading .env file from /var/srv/app/.env
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/index.ts`
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/index.ts`
Reading .env file from /var/srv/app/.env
Reading DB settings from file from /var/srv/app/ormconfig.json: 
 [object Object]
[2018-08-29T17:46:01.230] [INFO ] [TSED] - Scan files : /var/srv/app/src/controllers/current/**/*.ts
[2018-08-29T17:46:01.239] [INFO ] [TSED] - Scan files : /var/srv/app/src/controllers/v1/**/*.ts
[2018-08-29T17:46:01.251] [INFO ] [TSED] - Scan files : /var/srv/app/src/middlewares/**/*.ts
[2018-08-29T17:46:01.275] [INFO ] [TSED] - Scan files : /var/srv/app/src/services/**/*.ts
[2018-08-29T17:46:01.281] [INFO ] [TSED] - Scan files : /var/srv/app/src/converters/**/*.ts
[2018-08-29T17:46:01.345] [INFO ] [TSED] - settings.rootDir => /var/srv/app
[2018-08-29T17:46:01.345] [INFO ] [TSED] - settings.env => development
[2018-08-29T17:46:01.345] [INFO ] [TSED] - settings.httpPort => 3080
[2018-08-29T17:46:01.345] [INFO ] [TSED] - settings.httpsPort => 3090
[2018-08-29T17:46:01.346] [INFO ] [TSED] - settings.version => 1.0.0
[2018-08-29T17:46:01.346] [INFO ] [TSED] - settings.uploadDir => /var/srv/app/uploads
[2018-08-29T17:46:01.346] [INFO ] [TSED] - settings.debug => false
[2018-08-29T17:46:01.346] [INFO ] [TSED] - settings.logger => { logRequest: true }
[2018-08-29T17:46:01.349] [INFO ] [TSED] - settings.mount => { '/': '/var/srv/app/src/controllers/current/**/*.ts',
  '/v1': '/var/srv/app/src/controllers/v1/**/*.ts' }
[2018-08-29T17:46:01.350] [INFO ] [TSED] - settings.componentsScan => [ '/var/srv/app/src/middlewares/**/*.ts',
  '/var/srv/app/src/services/**/*.ts',
  '/var/srv/app/src/converters/**/*.ts' ]
[2018-08-29T17:46:01.351] [INFO ] [TSED] - settings.acceptMimes => [ 'application/json' ]
[2018-08-29T17:46:01.351] [INFO ] [TSED] - settings.httpsOptions => { key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 76 51 49 42 41 44 41 4e 42 67 6b 71 68 6b 69 47 39 77 ... >,
  cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 45 52 44 43 43 41 79 79 67 41 77 49 42 41 67 49 4a 41 50 ... >,
  passphrase: 'a6ff5a915c7d07c6f1b443d17af8d7c5ab3ed2d1',
  port: '3090' }
[2018-08-29T17:46:01.352] [INFO ] [TSED] - settings.typeorm => { db: 
   { name: 'default',
     type: 'postgres',
     host: 'project-db-postgresql',
     port: 5432,
     username: 'project',
     password: 'project',
     database: 'project',
     synchronize: true,
     logging: false,
     cache: { type: 'redis', options: [Object] },
     entities: [ 'src/entity/**/*.ts' ],
     migrations: [ 'src/entity/migrations/**/*.ts' ],
     subscribers: [ 'src/entity/subscribers/**/*.ts' ],
     cli: 
      { entitiesDir: 'src/entity',
        migrationsDir: 'src/entity/migrations',
        subscribersDir: 'src/entity/subscribers' } } }
[2018-08-29T17:46:01.352] [INFO ] [TSED] - settings.swagger => { path: '/api-docs' }
[2018-08-29T17:46:01.353] [INFO ] [TSED] - settings.customServiceOptions => {}
[2018-08-29T17:46:01.353] [INFO ] [TSED] - Build services
[2018-08-29T17:46:01.362] [INFO ] [TSED] - Connect to typeorm database: db
[2018-08-29T17:46:01.364] [ERROR] [TSED] - { AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
    at new AlreadyHasActiveConnectionError (/var/srv/app/src/error/AlreadyHasActiveConnectionError.ts:8:9)
    at ConnectionManager.create (/var/srv/app/src/connection/ConnectionManager.ts:57:23)
    at Object.<anonymous> (/var/srv/app/src/index.ts:218:35)
    at step (/var/srv/app/node_modules/typeorm/index.js:32:23)
    at Object.next (/var/srv/app/node_modules/typeorm/index.js:13:53)
    at /var/srv/app/node_modules/typeorm/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/var/srv/app/node_modules/typeorm/index.js:3:12)
    at Object.createConnection (/var/srv/app/node_modules/typeorm/index.js:215:12)
    at TypeORMService.<anonymous> (/var/srv/app/node_modules/@tsed/src/typeorm/services/TypeORMService.ts:27:7)
  name: 'AlreadyHasActiveConnectionError',
  message: 'Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.' }
[nodemon] clean exit - waiting for changes before restart
```

It's my index.js file (after I tried to create the database connection by my own) when I'm bootstraping the Server class...
```ts
import * as Fs from "fs";
import * as Path from "path";
import {getConnectionManager, createConnection, ConnectionManager, Connection} from "typeorm";
import envVars from "./bootstrap/env";
import {Server} from "./bootstrap/server";
import {UserRepository} from "./entity/repository/UserRepository";
import User from "./entity/User";

const rootDir = Path.resolve(__dirname+'/..');
const dbSettingsPath = `${rootDir}/ormconfig.json`;
const databaseSettings = JSON.parse(Fs.readFileSync(dbSettingsPath, 'utf8'));

createConnection().then(async connection => {
    let server = new Server(envVars, connection);
    server.start();
}).catch (error => {
    console.log(error);
});
```
And I don't know if I should create the connection by my own or not because if I try it there is an error and if not there is an error as well...

## Acceptance criterias

- [x] Example (log, usecase, etc...)
- [x] Ts.ED version (bug/question)

**Comment by sinner** [comment]
And I don't know if I should create the connection by my own or not because if I try it there is an error and if not there is an error as well...

**Comment by Romakita** [comment]
Hello @sinner ,
I've added a new example here https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-typeorm 
and fixed the documentation: http://tsed.io/tutorials/typeorm.html

For me the connection work as expected, but, I have another issue: EntityMetadataNotFound: No metadata for "User" was found. I don't know why, but I'll investigate on later.

Can you try my example and adapt the example on your project.

I saw in your configuration "name: default", can you remove this line and test it?
See you
Romain

**Comment by Romakita** [comment]
v4.30.6 fix some issue with `@tsed/typeorm` module. I added a complete example with postgresql here https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-typeorm 

See you :)

**Comment by sinner** [comment]
Hi @Romakita ! Yes, of course, I'll try to do it this weekend.
