### ISSUE TITLE
Error reported by SwaggerService

### ISSUE THREAD

**Issue by sinner** [Romakita/ts-express-decorators#443]
## Informations

Type | Version
---|---
Bug | 4.x

****

## Description
After running `npm start` using the Swagger integration of TS.ed I received an error (`TypeError: Cannot read property 'forEach' of undefined at SwaggerService.getOpenAPISpec`):

```sh
Reading .env file from /var/srv/app/.env
[2018-08-30T05:49:13.406] [INFO ] [TSED] - Scan files : /var/srv/app/src/controllers/current/**/*.ts
[2018-08-30T05:49:13.411] [INFO ] [TSED] - Scan files : /var/srv/app/src/controllers/v1/**/*.ts
[2018-08-30T05:49:13.419] [INFO ] [TSED] - Scan files : /var/srv/app/src/middlewares/**/*.ts
[2018-08-30T05:49:13.423] [INFO ] [TSED] - Scan files : /var/srv/app/src/services/**/*.ts
[2018-08-30T05:49:13.426] [INFO ] [TSED] - Scan files : /var/srv/app/src/converters/**/*.ts
[2018-08-30T05:49:13.476] [INFO ] [TSED] - settings.rootDir => /var/srv/app
[2018-08-30T05:49:13.476] [INFO ] [TSED] - settings.env => development
[2018-08-30T05:49:13.476] [INFO ] [TSED] - settings.httpPort => 3080
[2018-08-30T05:49:13.476] [INFO ] [TSED] - settings.httpsPort => 3090
[2018-08-30T05:49:13.476] [INFO ] [TSED] - settings.version => 1.0.0
[2018-08-30T05:49:13.476] [INFO ] [TSED] - settings.uploadDir => /var/srv/app/uploads
[2018-08-30T05:49:13.477] [INFO ] [TSED] - settings.debug => false
[2018-08-30T05:49:13.477] [INFO ] [TSED] - settings.logger => { logRequest: true }
[2018-08-30T05:49:13.479] [INFO ] [TSED] - settings.mount => { '/api/': '/var/srv/app/src/controllers/current/**/*.ts',
  '/api/v1': '/var/srv/app/src/controllers/v1/**/*.ts' }
[2018-08-30T05:49:13.480] [INFO ] [TSED] - settings.componentsScan => [ '/var/srv/app/src/middlewares/**/*.ts',
  '/var/srv/app/src/services/**/*.ts',
  '/var/srv/app/src/converters/**/*.ts' ]
[2018-08-30T05:49:13.480] [INFO ] [TSED] - settings.acceptMimes => [ 'application/json' ]
[2018-08-30T05:49:13.481] [INFO ] [TSED] - settings.httpsOptions => { key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 76 51 49 42 41 44 41 4e 42 67 6b 71 68 6b 69 47 39 77 ... >,
  cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 45 52 44 43 43 41 79 79 67 41 77 49 42 41 67 49 4a 41 50 ... >,
  passphrase: 'a6ff5a915c7d07c6f1b443d17af8d7c5ab3ed2d1',
  port: '3090' }
[2018-08-30T05:49:13.481] [INFO ] [TSED] - settings.swagger => { path: '/api-docs' }
[2018-08-30T05:49:13.481] [INFO ] [TSED] - settings.customServiceOptions => {}
[2018-08-30T05:49:13.482] [INFO ] [TSED] - Build services
[2018-08-30T05:49:13.533] [INFO ] [TSED] - Build controllers
[2018-08-30T05:49:13.542] [INFO ] [TSED] - Routes mounted :
[2018-08-30T05:49:13.545] [INFO ] [TSED] - 
┌──────────────────┬───────────────────┬──────────────────────────────────────┐
│ Method           │ Endpoint          │ Class method                         │
│──────────────────│───────────────────│──────────────────────────────────────│
│ GET              │ /api/user/        │ UserAccessController.list()          │
│──────────────────│───────────────────│──────────────────────────────────────│
│ POST             │ /api/user/sign-up │ UserAccessController.signUpAction()  │
│──────────────────│───────────────────│──────────────────────────────────────│
│ GET              │ /api/user/:id     │ UserAccessController.get()           │
│──────────────────│───────────────────│──────────────────────────────────────│
│ GET              │ /api/calendars/   │ CalendarController.renderCalendars() │
│──────────────────│───────────────────│──────────────────────────────────────│
│ POST             │ /api/calendars/   │ CalendarController.post()            │
│──────────────────│───────────────────│──────────────────────────────────────│
│ DELETE           │ /api/calendars/   │ CalendarController.deleteItem()      │
└──────────────────┴───────────────────┴──────────────────────────────────────┘
TypeError: Cannot read property 'forEach' of undefined
    at SwaggerService.getOpenAPISpec (/var/srv/app/node_modules/@tsed/src/swagger/services/SwaggerService.ts:165:35)
    at swagger.forEach (/var/srv/app/node_modules/@tsed/src/swagger/services/SwaggerService.ts:42:25)
    at Array.forEach (<anonymous>)
    at SwaggerService.$afterRoutesInit (/var/srv/app/node_modules/@tsed/src/swagger/services/SwaggerService.ts:40:13)
    at ProviderRegistry_1.ProviderRegistry.forEach (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:309:56)
    at Map.forEach (<anonymous>)
    at Registry.forEach (/var/srv/app/node_modules/@tsed/src/core/class/Registry.ts:140:19)
    at Function.<anonymous> (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:300:26)
    at Generator.next (<anonymous>)
    at /var/srv/app/node_modules/tslib/tslib.js:107:75
(node:375) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at SwaggerService.getOpenAPISpec (/var/srv/app/node_modules/@tsed/src/swagger/services/SwaggerService.ts:165:35)
    at swagger.forEach (/var/srv/app/node_modules/@tsed/src/swagger/services/SwaggerService.ts:42:25)
    at Array.forEach (<anonymous>)
    at SwaggerService.$afterRoutesInit (/var/srv/app/node_modules/@tsed/src/swagger/services/SwaggerService.ts:40:13)
    at ProviderRegistry_1.ProviderRegistry.forEach (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:309:56)
    at Map.forEach (<anonymous>)
    at Registry.forEach (/var/srv/app/node_modules/@tsed/src/core/class/Registry.ts:140:19)
    at Function.<anonymous> (/var/srv/app/node_modules/@tsed/src/common/di/services/InjectorService.ts:300:26)
    at Generator.next (<anonymous>)
    at /var/srv/app/node_modules/tslib/tslib.js:107:75
(node:375) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:375) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I was reviewing this source file SwaggerService.ts and I could see that there is a ControllerService that is trying to do a forEach into its property routes, but my IDE notifies me that this ControllerService doesn't have this property defined.

It's pretty weird, this error happens even if I haven't defined a decorator of Swagger into my Controller Classes.

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by Romakita** [comment]
It should be fixed with the latest release :)
