### ISSUE TITLE
Cannot use LogIncomingRequestMiddleware

### ISSUE THREAD

**Issue by avivVonage** [Romakita/ts-express-decorators#476]
## Informations

Type | Version
---|---
Bug | 4.32.0, 4.30.X

****

## Description
Hi,

I tried using [this](http://tsed.io/configuration.html#request-logger) guide to override the request logger, but couldn't do so.

First, I couldn't import `LogIncomingRequestMiddleware`. I checked the source code and saw that this class isn't exported in the index.ts file like the other components. So I added it manually to the file.

But now, when I run the project, I get a syntax error:
```
(function (exports, require, module, __filename, __dirname) { import { applyBefore } from '@tsed/core';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/acharikar/Documents/Iceberg-Auth/auth-service/node_modules/ts-node/src/index.ts:431:14)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
```

I tried both 4.32.0 and 4.30.X versions.

Thanks in advance!

**Comment by Romakita** [comment]
Ok I'll check that :)
