### ISSUE TITLE
Mongoose self reference issue (again)

### ISSUE THREAD

**Issue by oehm-smith** [Romakita/ts-express-decorators#513]
Following on from #316 - I am still getting this error.  I have upgraded all `@tsed` dependencies to `5.1.1`.

My model looks like (simplified to only 2 fields to minimise noise):

    import {Indexed, Model, Ref} from "@tsed/mongoose";
    import {PropertyType, Required} from "@tsed/common";

    @Model()
    export class Intent {
      @PropertyType(String)
      _id: string;

      @Ref(Intent)
      linkedIntents: Ref<Intent>[];
    }

Starting the server gives:

        error: undefined
        (node:19486) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
            at Array.forEach (<anonymous>)
            at JSON_SCHEMA_FIELDS.forEach (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/common/src/jsonschema/registries/JsonSchemesRegistry.ts:132:28)
            at Array.forEach (<anonymous>)
            at Map.findReferences (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/common/src/jsonschema/registries/JsonSchemesRegistry.ts:125:24)
            at Map.getSchema (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/common/src/jsonschema/registries/JsonSchemesRegistry.ts:110:10)
            at core_1.ancestorsOf.reduce (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/common/src/jsonschema/registries/JsonSchemesRegistry.ts:89:29)
            at Array.reduce (<anonymous>)
            at Map.getSchemaDefinition (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/common/src/jsonschema/registries/JsonSchemesRegistry.ts:88:32)
            at OpenApiModelSchemaBuilder.getClassSchema (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:117:40)
            at OpenApiModelSchemaBuilder.build (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:25:33)
            at OpenApiModelSchemaBuilder.createSchema (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:63:15)
            at properties.forEach (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:39:54)
            at Map.forEach (<anonymous>)
            at OpenApiModelSchemaBuilder.build (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:37:16)
            at OpenApiModelSchemaBuilder.createSchema (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:63:15)
            at properties.forEach (/Users/bbos/dev/dhs/bots/Bottal/express/node_modules/@tsed/swagger/src/class/OpenApiModelSchemaBuilder.ts:39:54)
        (node:19486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
        (node:19486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't believe this has been anything but a `string[]` until now, when I tried to make it a `Ref`.  As `linkedIntents: string[]`, it worked as expected.

**Comment by oehm-smith** [comment]
Can you reproduce this @Romakita ?

**Comment by Romakita** [comment]
Hi @oehm-smith 
The self referencing is a known problem. To solve it you can give a string name to the Ref decorator like this:
```typescript
import {Indexed, Model, Ref} from "@tsed/mongoose";
import {PropertyType, Required} from "@tsed/common";

@Model()
export class Intent {
  @PropertyType(String)
  _id: string;

  @Ref('Intent')   // <- use String Intent instead of Symbol
  linkedIntents: Ref<Intent>[];
}
```

**Comment by oehm-smith** [comment]
Great thanks Romain, that has fixed it.
