### ISSUE TITLE
error in debugging console when i using multiple classes or navigation 

### ISSUE THREAD

**Issue by SyedTariq358** [Romakita/ts-express-decorators#515]
npm 6.8.0
window 10
vs code
when i using navigation these errors will give how to fix it?

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
Waiting for the debugger to disconnect...
SyntaxError: Unexpected identifier
vm.js:79
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)

**Comment by Romakita** [comment]
@SyedTariq358 I don't use vscode... but your error means, the typescript isn't compiled by your IDE. Look on google how to configure vscode to run typescript code ?

**Comment by SyedTariq358** [comment]
thank you for reply its also give me error of importing React from react in
the first line what should i do ?

**Comment by Romakita** [comment]
Hum I don't understand why you have a problem with React. Ts.ED is a backend framework and I can't give you a solution for other problem not related to Ts.ED ;)
