### ISSUE TITLE
Can't test endpoint with SuperTest when it uses an overriden middleware.

### ISSUE THREAD

**Issue by Szauka** [Romakita/ts-express-decorators#516]
## Information

- **Version:** 5.1.3
- **Type:** Issue

## Description
Can't test the failing path of an endpoint when it uses an overridden middleware.

## Example

```typescript
import { ExpressApplication } from '@tsed/common';
import { TestContext } from '@tsed/testing';
import * as Path from 'path';
import * as SuperTest from 'supertest';
import { Server } from '../../../../src/app';

describe('Archive endpoint', () => {

    // bootstrap the express application
    before(TestContext.bootstrap(Server));
    before(TestContext.inject([ExpressApplication], (expressApplication: ExpressApplication) => {
        this.app = expressApplication;
    }));
    after(TestContext.reset);


    describe('PUT /api/upload', () => {

        it('should return 401', (done) => {
            SuperTest(this.app)
                .put('/api/upload')
                .attach('file', Path.join(__dirname, '/test.txt'))
                .expect(400)
                .end((err, res: any) => {
                    if (err || !res.OK) {
                        throw (err);
                    }

                    done();
                });
        });
    });
});
```

Throws: 
```
1) Archive endpoint
       PUT /api/upload
         should return 401:
     Uncaught Error: write ECONNABORTED
      at _errnoException (util.js:1022:11)
      at Socket._writeGeneric (net.js:767:25)
      at Socket._write (net.js:786:8)
      at doWrite (_stream_writable.js:387:12)
      at clearBuffer (_stream_writable.js:514:7)
      at Socket.Writable.uncork (_stream_writable.js:313:7)
      at connectionCorkNT (_http_outgoing.js:685:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Acceptance criteria

I would expect it to pass.

Repo to replicate the issue: https://github.com/Szauka/errorReplication

**Comment by Romakita** [comment]
Thanks @Szauka I'll try your example and fix the problem ;)

**Comment by Romakita** [comment]
Ok I found the issue. Your test isn't correctly written ;)
I sent you a PR on your repo.

See you
Romain

**Comment by Szauka** [comment]
Hi @Romakita ,

I was still getting the error. 
It turns out that the issue was with my environment as it was working on other PC. 
Reinstalling node fixed the problem.

Thanks a lot for looking into this.
