### ISSUE TITLE
1.4.9 Injector problem

### ISSUE THREAD

**Issue by rdinicut** [Romakita/ts-express-decorators#72]
Just made an update to 1.4.9 and I get an error when i start the server:

```
node_modules/ts-express-decorators/src/services/injector.ts:208
    static get = <T>(target): T => InjectorService.providers.get(getClassOrSymbol(target)).instance;
                                                                                          ^
TypeError: Cannot read property 'instance' of undefined
```
Works fine with 1.4.8. 

Any ideas on what it's happening?

Thanks

**Comment by Romakita** [comment]
I @rdinicut,

I'll check this bug ASAP. 

See you

**Comment by Romakita** [comment]
Hi @rdinicut,
Can you send me the complete log please ? Because I haven't idea ^^.

Thanks,
Romain

**Comment by rdinicut** [comment]
`/Users/razvan/Workspace/Connect/service-buying-interface/node_modules/ts-express-decorators/src/services/injector.ts:208
    static get = <T>(target): T => InjectorService.providers.get(getClassOrSymbol(target)).instance;
                                                                                          ^
TypeError: Cannot read property 'instance' of undefined
    at Function.InjectorService.get (/Users/razvan/Workspace/Connect/service-buying-interface/node_modules/ts-express-decorators/src/services/injector.ts:208:91)
    at ServerLoader.start (/Users/razvan/Workspace/Connect/service-buying-interface/node_modules/ts-express-decorators/src/server/server-loader.ts:308:42)
    at Object.<anonymous> (/Users/razvan/Workspace/Connect/service-buying-interface/dist/server/server.js:52:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)`

**Comment by Romakita** [comment]
Hi @rdinicut ,

It's fixed. v1.4.10 is released :)

Thanks for you report,
Romai
