### ISSUE TITLE
Socket.io Integration is not working

### ISSUE THREAD

**Issue by jindev** [Romakita/ts-express-decorators#89]
## Informations
Integrating Socket.io according to [Doc](https://romakita.github.io/ts-express-decorators/#/tutorials/socket-io?id=how-to-integrate-socketio) is not working.

Type | Version
Question|2.0.0-4

****

## Description
As Doc, HttpServer should be injected in SocketService constructor. but HttpServer is private and it is not exported.
I just want to know whether current document is outupdated or the part of socket.io integration is not developed yet.
Thank you.

```
[1] [2017-08-18 15:04:28.280] [ERROR] [TSED] - TypeError: Cannot use 'in' operator to search for '$beforeRoutesInit' in undefined
[1]     at /Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:407:26
[1]     at Map.forEach (native)
[1]     at Registry.forEach (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/core/class/Registry.ts:125:19)
[1]     at Function.<anonymous> (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:403:26)
[1]     at step (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:42:23)
[1]     at Object.next (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:23:53)
[1]     at /Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:17:71
[1]     at Promise (<anonymous>)
[1]     at __awaiter (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:13:12)
[1]     at Function.InjectorService.emit (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:370:16)
[1]     at InjectorService.emit (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:129:36)
[1]     at Server.<anonymous> (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/server/components/ServerLoader.ts:236:36)
[1]     at step (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/server/components/ServerLoader.js:49:23)
[1]     at Object.next (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/server/components/ServerLoader.js:30:53)
[1]     at fulfilled (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/server/components/ServerLoader.js:21:58)
[1]     at <anonymous>
[1]     at process._tickCallback (internal/process/next_tick.js:188:7)
[1]     at Function.Module.runMain (module.js:607:11)
[1]     at startup (bootstrap_node.js:158:16)
[1]     at bootstrap_node.js:575:3
[1] [2017-08-18 15:04:28.300] [INFO ] [TSED] - start server
[1] (node:5317) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): INJECTION_ERROR: Service SocketService > Object not found.
[1] (node:5317) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by jindev** [comment]
Here is error.
```
[1] [2017-08-18 15:04:28.280] [ERROR] [TSED] - TypeError: Cannot use 'in' operator to search for '$beforeRoutesInit' in undefined
[1]     at /Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:407:26
[1]     at Map.forEach (native)
[1]     at Registry.forEach (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/core/class/Registry.ts:125:19)
[1]     at Function.<anonymous> (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:403:26)
[1]     at step (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:42:23)
[1]     at Object.next (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:23:53)
[1]     at /Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:17:71
[1]     at Promise (<anonymous>)
[1]     at __awaiter (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:13:12)
[1]     at Function.InjectorService.emit (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/di/services/InjectorService.js:370:16)
[1]     at InjectorService.emit (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/di/services/InjectorService.ts:129:36)
[1]     at Server.<anonymous> (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/src/server/components/ServerLoader.ts:236:36)
[1]     at step (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/server/components/ServerLoader.js:49:23)
[1]     at Object.next (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/server/components/ServerLoader.js:30:53)
[1]     at fulfilled (/Users/bjkim/Desktop/flitto/vitamin/node_modules/ts-express-decorators/lib/server/components/ServerLoader.js:21:58)
[1]     at <anonymous>
[1]     at process._tickCallback (internal/process/next_tick.js:188:7)
[1]     at Function.Module.runMain (module.js:607:11)
[1]     at startup (bootstrap_node.js:158:16)
[1]     at bootstrap_node.js:575:3
[1] [2017-08-18 15:04:28.300] [INFO ] [TSED] - start server
[1] (node:5317) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): INJECTION_ERROR: Service SocketService > Object not found.
[1] (node:5317) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
